//! Indonesian stop words (from Lucene/Snowball project).

use alloc::borrow::Cow;
use alloc::vec::Vec;
use hashbrown::HashSet;
use once_cell::sync::Lazy;
use pizza_engine::analysis::{Token, TokenFilter};

/// Default Indonesian stop words sourced from Apache Lucene.
static DEFAULT_STOP_WORDS: Lazy<HashSet<&'static str>> = Lazy::new(|| {
    let words: &[&str] = &[
    "ada",
    "adalah",
    "adanya",
    "adapun",
    "agak",
    "agaknya",
    "agar",
    "akan",
    "akankah",
    "akhirnya",
    "aku",
    "akulah",
    "amat",
    "amatlah",
    "anda",
    "andalah",
    "antar",
    "antara",
    "antaranya",
    "apa",
    "apaan",
    "apabila",
    "apakah",
    "apalagi",
    "apatah",
    "atau",
    "ataukah",
    "ataupun",
    "bagai",
    "bagaikan",
    "bagaimana",
    "bagaimanakah",
    "bagaimanapun",
    "bagi",
    "bahkan",
    "bahwa",
    "bahwasanya",
    "banyak",
    "beberapa",
    "begini",
    "beginian",
    "beginikah",
    "beginilah",
    "begitu",
    "begitukah",
    "begitulah",
    "begitupun",
    "belum",
    "belumlah",
    "berapa",
    "berapakah",
    "berapalah",
    "berapapun",
    "bermacam",
    "bersama",
    "betulkah",
    "biasa",
    "biasanya",
    "bila",
    "bilakah",
    "bisa",
    "bisakah",
    "boleh",
    "bolehkah",
    "bolehlah",
    "buat",
    "bukan",
    "bukankah",
    "bukanlah",
    "bukannya",
    "cuma",
    "dahulu",
    "dalam",
    "dan",
    "dapat",
    "dari",
    "daripada",
    "dekat",
    "demi",
    "demikian",
    "demikianlah",
    "dengan",
    "depan",
    "di",
    "dia",
    "dialah",
    "diantara",
    "diantaranya",
    "dikarenakan",
    "dini",
    "diri",
    "dirinya",
    "disini",
    "disinilah",
    "dong",
    "dulu",
    "enggak",
    "enggaknya",
    "entah",
    "entahlah",
    "hal",
    "hampir",
    "hanya",
    "hanyalah",
    "harus",
    "haruslah",
    "harusnya",
    "hendak",
    "hendaklah",
    "hendaknya",
    "hingga",
    "ia",
    "ialah",
    "ibarat",
    "ingin",
    "inginkah",
    "inginkan",
    "ini",
    "inikah",
    "inilah",
    "itu",
    "itukah",
    "itulah",
    "jangan",
    "jangankan",
    "janganlah",
    "jika",
    "jikalau",
    "juga",
    "justru",
    "kala",
    "kalau",
    "kalaulah",
    "kalaupun",
    "kalian",
    "kami",
    "kamilah",
    "kamu",
    "kamulah",
    "kan",
    "kapan",
    "kapankah",
    "kapanpun",
    "karena",
    "karenanya",
    "ke",
    "kecil",
    "kemudian",
    "kenapa",
    "kepada",
    "kepadanya",
    "ketika",
    "khususnya",
    "kini",
    "kinilah",
    "kiranya",
    "kita",
    "kitalah",
    "kok",
    "lagi",
    "lagian",
    "lah",
    "lain",
    "lainnya",
    "lalu",
    "lama",
    "lamanya",
    "lebih",
    "macam",
    "maka",
    "makanya",
    "makin",
    "malah",
    "malahan",
    "mampu",
    "mampukah",
    "mana",
    "manakala",
    "manalagi",
    "masih",
    "masihkah",
    "masing",
    "mau",
    "maupun",
    "melainkan",
    "melalui",
    "memang",
    "mengapa",
    "mereka",
    "merekalah",
    "merupakan",
    "meski",
    "meskipun",
    "mungkin",
    "mungkinkah",
    "nah",
    "namun",
    "nanti",
    "nantinya",
    "nyaris",
    "oleh",
    "olehnya",
    "pada",
    "padahal",
    "padanya",
    "paling",
    "pantas",
    "para",
    "pasti",
    "pastilah",
    "per",
    "percuma",
    "pernah",
    "pula",
    "pun",
    "rupanya",
    "saat",
    "saatnya",
    "saja",
    "sajalah",
    "saling",
    "sama",
    "sambil",
    "sampai",
    "sana",
    "sangat",
    "sangatlah",
    "saya",
    "sayalah",
    "se",
    "sebab",
    "sebabnya",
    "sebagai",
    "sebagaimana",
    "sebagainya",
    "sebaliknya",
    "sebanyak",
    "sebegini",
    "sebegitu",
    "sebelum",
    "sebelumnya",
    "sebenarnya",
    "seberapa",
    "sebetulnya",
    "sebisanya",
    "sebuah",
    "sedang",
    "sedangkan",
    "sedemikian",
    "sedikit",
    "sedikitnya",
    "segala",
    "segalanya",
    "segera",
    "seharusnya",
    "sehingga",
    "sejak",
    "sejenak",
    "sekali",
    "sekalian",
    "sekaligus",
    "sekalipun",
    "sekarang",
    "seketika",
    "sekiranya",
    "sekitar",
    "sekitarnya",
    "sela",
    "selagi",
    "selain",
    "selaku",
    "selalu",
    "selama",
    "selamanya",
    "seluruh",
    "seluruhnya",
    "semacam",
    "semakin",
    "semasih",
    "semaunya",
    "sementara",
    "sempat",
    "semua",
    "semuanya",
    "semula",
    "sendiri",
    "sendirinya",
    "seolah",
    "seorang",
    "sepanjang",
    "sepantasnya",
    "sepantasnyalah",
    "seperti",
    "sepertinya",
    "sering",
    "seringnya",
    "serta",
    "serupa",
    "sesaat",
    "sesama",
    "sesegera",
    "sesekali",
    "seseorang",
    "sesuatu",
    "sesuatunya",
    "sesudah",
    "sesudahnya",
    "setelah",
    "seterusnya",
    "setiap",
    "setidaknya",
    "sewaktu",
    "siapa",
    "siapakah",
    "siapapun",
    "sini",
    "sinilah",
    "suatu",
    "sudah",
    "sudahkah",
    "sudahlah",
    "supaya",
    "tadi",
    "tadinya",
    "tak",
    "tanpa",
    "tapi",
    "telah",
    "tentang",
    "tentu",
    "tentulah",
    "tentunya",
    "terdiri",
    "terhadap",
    "terhadapnya",
    "terlalu",
    "terlebih",
    "tersebut",
    "tersebutlah",
    "tertentu",
    "tetapi",
    "tiap",
    "tidak",
    "tidakkah",
    "tidaklah",
    "toh",
    "waduh",
    "wah",
    "wahai",
    "walau",
    "walaupun",
    "wong",
    "yaitu",
    "yakni",
    "yang",
    ];
    words.iter().copied().collect()
});

/// Removes Indonesian stop words from the token stream.
#[derive(Clone, Debug)]
pub struct IndonesianStopFilter {
    stop_words: HashSet<String>,
}

impl Default for IndonesianStopFilter {
    fn default() -> Self {
        Self::new()
    }
}

impl IndonesianStopFilter {
    pub fn new() -> Self {
        Self {
            stop_words: DEFAULT_STOP_WORDS.iter().map(|s| s.to_string()).collect(),
        }
    }

    pub fn with_words(words: &[&str]) -> Self {
        Self {
            stop_words: words.iter().map(|s| s.to_string()).collect(),
        }
    }
}

impl TokenFilter for IndonesianStopFilter {
    fn filter<'a>(&self, token: &mut Token<'a>) -> (bool, Option<Vec<Token<'a>>>) {
        let term = token.term.as_ref();
        if self.stop_words.contains(term) {
            return (true, None);
        }
        (false, None)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_stop_word_count() {
        assert!(DEFAULT_STOP_WORDS.len() >= 355);
    }

    #[test]
    fn test_filters_stop_word() {
        let f = IndonesianStopFilter::new();
        let word = DEFAULT_STOP_WORDS.iter().next().unwrap();
        let mut token = Token::new(word, 0, word.len() as u32, 0);
        let (deleted, _) = f.filter(&mut token);
        assert!(deleted);
    }

    #[test]
    fn test_passes_non_stop_word() {
        let f = IndonesianStopFilter::new();
        let mut token = Token::new("xyzzy_not_a_stop_word", 0, 21, 0);
        let (deleted, _) = f.filter(&mut token);
        assert!(!deleted);
    }

    #[test]
    fn test_custom_words() {
        let f = IndonesianStopFilter::with_words(&["custom", "words"]);
        let mut token = Token::new("custom", 0, 6, 0);
        let (deleted, _) = f.filter(&mut token);
        assert!(deleted);
    }
}
